### ISSUE TITLE
ReferenceError: title is not defined

### ISSUE THREAD

**Issue by fanyangyang** [nebulasio/go-nebulas#180]
```
ERRO[2018-12-05T07:22:42Z] V8 Exception:
lib/contract.js:85
            title:title,
                  ^
ReferenceError: title is not defined
    at EggContract.save (lib/contract.js:85:19)
    at _contract_runner.js:5:29  file=logger.go func=nvm.V8Log line=32
```
使用的是v1.0.8.1的release，在同步测试网数据的过程中出现了问题，能否帮忙解决一下

**Comment by Samuelchen85** [comment]
你好，这个在同步时出现是正常的，因为历史交易记录里该次合约调用就是有错误的。如果同步因为V8执行超时停止，可参考 #152 解决。

**Comment by fanyangyang** [comment]
设置较长的超时时间会导致出现null的情况，也算是异常情况，不过重启一下后又开始继续同步了，谢谢
