### ISSUE TITLE
Nebulas smart contract conditional expression not work

### ISSUE THREAD

**Issue by qywang2012** [nebulasio/go-nebulas#54]
For nebulas smart contract, we can't write a conditional expression in a smart contract. 
If a contract contains a conditional expression like this:

```js
balanceOf: function (owner) {
       var balance = this.balances.get(owner);
       return (typeof balance != “undefined”) ? balance.toString() : “0";
   },
```
an error will be throwed when running the contract:

```
The _instruction_counter make it throw error

time=“2018-01-31T17:01:02+08:00” level=error msg=“V8 Exception:\nlib/contract.js:114\n        return (!_instruction_counter.incr(6) || typeof balance != \“undefined\“) ? !_instruction_counter.incr(12) || balance.toString() : \“0\“;\n                                                                                                                            ^\nTypeError: Cannot read property ‘toString’ of null\n    at StandardToken.balanceOf (lib/contract.js:114:125)\n    at _contract_runner.js:5:56” file=logger.go func=nvm.V8Log line=32
```
From the error log, NVM added `_instruction_counter` when executing the contract. Instruction_counter is used to count gas consumption.

**Comment by fbzhong** [comment]
Hi Larry,

I check the following code, `instruction_counter.js` works well.

```javascript
function test(balance) {
        return (typeof balance != "undefined") ? balance.toString() : "0";
}

console.log(test());
console.log(test("123"));
```

After processing by `instruction_counter.js`, the output is:
```javascript
function test(balance) {
        return (!_instruction_counter.incr(6) || typeof balance != "undefined") ? !_instruction_counter.incr(12) || balance.toString() : "0";
}

_instruction_counter.incr(20);console.log(test());
_instruction_counter.incr(20);console.log(test("123"));
```
